version: "3.9"
services:
  app:
    container_name: devops_nodos_app
    build:
      context: .
      dockerfile: Dockerfile.production
    depends_on:
      - db
    command: npm test
  
  db:
    container_name: devops_nodos_app_db
    image: postgres:11.12
    restart: always
    environment:
      POSTGRES_PASSWORD: "${NODOS_DB_PASSWORD}"
      POSTGRES_USER: "${NODOS_DB_USERNAME}"
